### ISSUE TITLE
Beatmap corrupt when it is not corrupt.

### ISSUE THREAD

**Issue by lualex403** [Tillerino/Tillerinobot#187] opened 2020-07-11 04:17 UTC
https://osu.ppy.sh/beatmapsets/1211207#osu/2521604 when I try to use tillerino for the extra difficulty it says the beatmap is corrupt however, when I copy and paste the difficulty and change the name, it works once, then when i try again it says beatmap corrupt

**Comment by Tillerino** [comment] 2020-07-11 08:16
Weird, lemme take a look.

**Comment by Tillerino** [comment] 2020-08-14 06:28
Hi @lualex403, I could not reproduce the problem. Can you send a screenshot of what you're doing or something?

**Comment by Tillerino** [comment] 2022-01-02 21:32
Gonna close this since no follow-up

**Closed by Tillerino** 2022-01-02 21:32 UTC
